version = 0.1

[default.deploy.parameters]
stack_name = "webhook-staging"
resolve_s3 = true
s3_prefix = "webhook-staging"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\" AlarmEmail=\"stephensoftware7@gmail.com\""
image_repositories = []
disable_rollback = true
